# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "dtac"
license = "MIT"
licenselink = "https://github.com/solvire/data-tactical/blob/master/LICENSE.md"
description = "Corporate Theme"
homepage = "https://dtac.io/"
tags = ["ghost", "minimal"]
features = ["", ""]
min_version = 0.15

[author]
  name = " dasalvar"

# If porting an existing theme
[original]
  name = "Peter Amende"
  homepage = "https://github.com/zutrinken"
  repo = "https://github.com/zutrinken/bleak"
